/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminBeveragesRouteImport } from './routes/admin.beverages'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminHoursRouteImport } from './routes/admin.hours'
import { Route as AdminKitchenRouteImport } from './routes/admin.kitchen'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminVisitDetailsRouteImport } from './routes/admin.visit-details'
import { Route as GalleryImageSplatRouteImport } from './routes/gallery-image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeveragesRoute = AdminBeveragesRouteImport.update({
  id: '/beverages',
  path: '/beverages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitDetailsRoute = AdminVisitDetailsRouteImport.update({
  id: '/visit-details',
  path: '/visit-details',
  getParentRoute: () => AdminRoute,
} as any)
const GalleryImageSplatRoute = GalleryImageSplatRouteImport.update({
  id: '/gallery-image/$',
  path: '/gallery-image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/reservations': typeof ReservationsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/beverages': typeof AdminBeveragesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/visit-details': typeof AdminVisitDetailsRoute
  '/gallery-image/$': typeof GalleryImageSplatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/reservations': typeof ReservationsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/beverages': typeof AdminBeveragesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/visit-details': typeof AdminVisitDetailsRoute
  '/gallery-image/$': typeof GalleryImageSplatRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/reservations': typeof ReservationsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/beverages': typeof AdminBeveragesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/visit-details': typeof AdminVisitDetailsRoute
  '/gallery-image/$': typeof GalleryImageSplatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/events'
    | '/experience'
    | '/gallery'
    | '/menu'
    | '/our-story'
    | '/reservations'
    | '/admin/activity'
    | '/admin/beverages'
    | '/admin/contact'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/hours'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/staff'
    | '/admin/visit-details'
    | '/gallery-image/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/events'
    | '/experience'
    | '/gallery'
    | '/menu'
    | '/our-story'
    | '/reservations'
    | '/admin/activity'
    | '/admin/beverages'
    | '/admin/contact'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/hours'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/staff'
    | '/admin/visit-details'
    | '/gallery-image/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/events'
    | '/experience'
    | '/gallery'
    | '/menu'
    | '/our-story'
    | '/reservations'
    | '/admin/activity'
    | '/admin/beverages'
    | '/admin/contact'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/hours'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/staff'
    | '/admin/visit-details'
    | '/gallery-image/$'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ExperienceRoute: typeof ExperienceRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  OurStoryRoute: typeof OurStoryRoute
  ReservationsRoute: typeof ReservationsRoute
  GalleryImageSplatRoute: typeof GalleryImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beverages': {
      id: '/admin/beverages'
      path: '/beverages'
      fullPath: '/admin/beverages'
      preLoaderRoute: typeof AdminBeveragesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hours': {
      id: '/admin/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visit-details': {
      id: '/admin/visit-details'
      path: '/visit-details'
      fullPath: '/admin/visit-details'
      preLoaderRoute: typeof AdminVisitDetailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/gallery-image/$': {
      id: '/gallery-image/$'
      path: '/gallery-image/$'
      fullPath: '/gallery-image/$'
      preLoaderRoute: typeof GalleryImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBeveragesRoute: typeof AdminBeveragesRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHoursRoute: typeof AdminHoursRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminVisitDetailsRoute: typeof AdminVisitDetailsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminBeveragesRoute: AdminBeveragesRoute,
  AdminContactRoute: AdminContactRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHoursRoute: AdminHoursRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminVisitDetailsRoute: AdminVisitDetailsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ExperienceRoute: ExperienceRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  OurStoryRoute: OurStoryRoute,
  ReservationsRoute: ReservationsRoute,
  GalleryImageSplatRoute: GalleryImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
