/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminKitchenRouteImport } from './routes/admin.kitchen'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/reservations': typeof ReservationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/reservations': typeof ReservationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/reservations': typeof ReservationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/events'
    | '/experience'
    | '/gallery'
    | '/menu'
    | '/our-story'
    | '/reservations'
    | '/admin/enquiries'
    | '/admin/kitchen'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/events'
    | '/experience'
    | '/gallery'
    | '/menu'
    | '/our-story'
    | '/reservations'
    | '/admin/enquiries'
    | '/admin/kitchen'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/events'
    | '/experience'
    | '/gallery'
    | '/menu'
    | '/our-story'
    | '/reservations'
    | '/admin/enquiries'
    | '/admin/kitchen'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ExperienceRoute: typeof ExperienceRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  OurStoryRoute: typeof OurStoryRoute
  ReservationsRoute: typeof ReservationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ExperienceRoute: ExperienceRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  OurStoryRoute: OurStoryRoute,
  ReservationsRoute: ReservationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
